name: ci 

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo 
        uses: actions/checkout@4

      - name: setup python 
        uses: actions/setup-python@5
        with:
          python:version: "3.10"

      - name: install dependencies 
        run: pip install -r requirements.txt 

      - name: Run tests
        run: pytest 
